### ISSUE TITLE
Implement ECS Fargate with Atlantis Service task

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-root-modules#90]
## what
* Implement an ECS Fargate cluster
* Deploy one app (atlantis) using the `cloudposse/terraform-aws-ecs-*` modules.
* Use codebuild/codepipeline to CI/CD apps (supported by modules already. see below).

## why
* Use Atlantis for terraform GitOps

## use-case
* Deploying geodesic account containers with atlantis 

## todo
- [x] Add ECS Fargate cluster
- [x] Add [ACM certificates](https://github.com/cloudposse/terraform-aws-acm-request-certificate) 
- [x] Add [ALB](https://github.com/cloudposse/terraform-aws-alb) and associate with ACM certificates
- [x] Setup DNS with ALB
- [x] Add [slack integration](https://github.com/cloudposse/terraform-aws-sns-lambda-notify-slack) with SNS
- [x] Use [default backend](https://github.com/cloudposse/default-backend) as a 404 controller (like in k8s)
- [x] [Deploy atlantis as an example app](https://github.com/cloudposse/terraform-aws-ecs-web-app)
- [x] [Generate SSH key pair and write it to SSM](https://github.com/cloudposse/terraform-aws-ssm-tls-ssh-key-pair)
- [x] Write as many settings (e.g. all the `ATLANTIS_*` env vars) for atlantis as possible using [`ssm_parameters`](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html) so we don't need to do much on the command line. E.g. if it can be computed, then write it. E.g. compute the atlantis URL. Compute the atlantis webhook secret.

**Comment by osterman** [comment]
@joshmyers I've pushed some incomplete boilerplate code that implements in snippets of what we need. I need your help to get it all working.

**Comment by joshmyers** [comment]
Closed by https://github.com/cloudposse/terraform-root-modules/pull/91
